{
  "configs": {
    "libFiles": [
      "/lib/secThread.js",
      "/lib/growThread.js",
      "/lib/hackThread.js",
      "/lib/shareThread.js"
    ]
  },
  "playerData": {
    "hp": {
      "current": 10,
      "max": 10
    },
    "skills": {
      "hacking": 337,
      "strength": 1,
      "defense": 1,
      "dexterity": 1,
      "agility": 1,
      "charisma": 1,
      "intelligence": 0
    },
    "exp": {
      "hacking": 244835.0856380923,
      "strength": 0,
      "defense": 0,
      "dexterity": 0,
      "agility": 0,
      "charisma": 0,
      "intelligence": 0
    },
    "mults": {
      "hacking_chance": 1.3575925566963085,
      "hacking_speed": 1.3594084459024138,
      "hacking_money": 1.416082938957601,
      "hacking_grow": 1.2313764686587838,
      "hacking": 1.7100290147848975,
      "hacking_exp": 2.044469743120037,
      "strength": 1.2313764686587838,
      "strength_exp": 1.5576912328533612,
      "defense": 1.2313764686587838,
      "defense_exp": 1.5576912328533612,
      "dexterity": 1.7066877855610743,
      "dexterity_exp": 1.5576912328533612,
      "agility": 1.357592556696309,
      "agility_exp": 1.5576912328533612,
      "charisma": 1.4776517623905405,
      "charisma_exp": 1.5576912328533612,
      "hacknet_node_money": 1.4899655270771286,
      "hacknet_node_purchase_cost": 0.730889393217235,
      "hacknet_node_ram_cost": 0.8120993257969278,
      "hacknet_node_core_cost": 0.8120993257969278,
      "hacknet_node_level_cost": 0.6902844269273886,
      "company_rep": 1.2313764686587838,
      "faction_rep": 1.2313764686587838,
      "work_money": 1.2313764686587838,
      "crime_success": 1.2313764686587838,
      "crime_money": 1.3545141155246623,
      "bladeburner_max_stamina": 1,
      "bladeburner_stamina_gain": 1,
      "bladeburner_analysis": 1,
      "bladeburner_success_chance": 1
    },
    "city": "Sector-12",
    "numPeopleKilled": 0,
    "money": 61383466.11253552,
    "location": "Travel Agency",
    "totalPlaytime": 1085827200,
    "jobs": {},
    "factions": [
      "NiteSec"
    ],
    "entropy": 0,
    "karma": -20.439999999999984,
    "playtimeSinceLastAug": 4137800,
    "hasTor": true,
    "time": 4138600,
    "ownedAugmentations": [
      "Cranial Signal Processors - Gen I",
      "Cranial Signal Processors - Gen II",
      "BitWire",
      "Neurotrainer I",
      "Synaptic Enhancement Implant",
      "NeuroFlux Governor",
      "Neural-Retention Enhancement",
      "Embedded Netburner Module",
      "Neurotrainer II",
      "Artificial Synaptic Potentiation",
      "Speech Processor Implant",
      "Augmented Targeting I",
      "Wired Reflexes",
      "Cranial Signal Processors - Gen III",
      "CashRoot Starter Kit",
      "Augmented Targeting II",
      "LuminCloaking-V1 Skin Implant",
      "Hacknet Node Cache Architecture Neural-Upload",
      "Hacknet Node NIC Architecture Neural-Upload"
    ],
    "completedFactions": {
      "CyberSec": true,
      "NiteSec": true,
      "Sector-12": true
    }
  },
  "serverTree": {
    "home": {
      "hops": 0,
      "links": [
        "n00dles",
        "foodnstuff",
        "sigma-cosmetics",
        "joesguns",
        "hong-fang-tea",
        "harakiri-sushi",
        "iron-gym",
        "darkweb",
        "nectar-net",
        "neo-net",
        "CSEC",
        "max-hardware",
        "zer0",
        "silver-helix",
        "phantasy",
        "omega-net",
        "avmnite-02h",
        "crush-fitness",
        "johnson-ortho",
        "the-hub"
      ],
      "hostname": "home",
      "ip": "90.8.5.4",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": true,
      "httpPortOpen": true,
      "sqlPortOpen": true,
      "hasAdminRights": true,
      "cpuCores": 1,
      "isConnectedTo": true,
      "ramUsed": 1013.95,
      "maxRam": 1024,
      "organizationName": "Home PC",
      "purchasedByPlayer": true,
      "backdoorInstalled": false,
      "baseDifficulty": 1,
      "hackDifficulty": 1,
      "minDifficulty": 1,
      "moneyAvailable": 61383466.11253552,
      "moneyMax": 0,
      "numOpenPortsRequired": 5,
      "openPortCount": 5,
      "requiredHackingSkill": 1,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "n00dles": {
      "parent": "home",
      "hops": 1,
      "links": [
        "home"
      ],
      "hostname": "n00dles",
      "ip": "36.1.4.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 1,
      "isConnectedTo": false,
      "ramUsed": 3.5,
      "maxRam": 4,
      "organizationName": "Noodle Bar",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 1,
      "hackDifficulty": 1.084,
      "minDifficulty": 1,
      "moneyAvailable": 195495.98657217697,
      "moneyMax": 196875,
      "numOpenPortsRequired": 0,
      "openPortCount": 2,
      "requiredHackingSkill": 1,
      "serverGrowth": 3000,
      "timeNextHack": 4139377.7849695487,
      "timeNextGrow": 4143488.9119025557,
      "timeNextWeaken": 4143109.9993912415,
      "hasAdminrights": true
    },
    "foodnstuff": {
      "parent": "home",
      "hops": 1,
      "links": [
        "home",
        "max-hardware"
      ],
      "hostname": "foodnstuff",
      "ip": "80.5.5.7",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 1,
      "isConnectedTo": false,
      "ramUsed": 14.95,
      "maxRam": 16,
      "organizationName": "FoodNStuff",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 10,
      "hackDifficulty": 3.0300000000000002,
      "minDifficulty": 3,
      "moneyAvailable": 1099846.0254391097,
      "moneyMax": 5625000,
      "numOpenPortsRequired": 0,
      "openPortCount": 2,
      "requiredHackingSkill": 1,
      "serverGrowth": 5,
      "timeNextHack": 3861088.463705076,
      "timeNextGrow": 4152036.871076644,
      "timeNextWeaken": 4157896.0888458053,
      "hasAdminrights": true
    },
    "max-hardware": {
      "parent": "home",
      "hops": 1,
      "links": [
        "foodnstuff",
        "silver-helix",
        "home"
      ],
      "hostname": "max-hardware",
      "ip": "18.7.2.3",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 2,
      "isConnectedTo": false,
      "ramUsed": 32,
      "maxRam": 32,
      "organizationName": "Max Hardware Store",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 15,
      "hackDifficulty": 9.55,
      "minDifficulty": 5,
      "moneyAvailable": 7500000,
      "moneyMax": 28125000,
      "numOpenPortsRequired": 1,
      "openPortCount": 2,
      "requiredHackingSkill": 80,
      "serverGrowth": 30,
      "timeNextHack": 4149104.779647535,
      "timeNextGrow": 4155685.1790557182,
      "timeNextWeaken": 4207219.11859014,
      "hasAdminrights": true
    },
    "silver-helix": {
      "parent": "home",
      "hops": 1,
      "links": [
        "max-hardware",
        "home"
      ],
      "hostname": "silver-helix",
      "ip": "93.2.9.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 62.5,
      "maxRam": 64,
      "organizationName": "Silver Helix",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 30,
      "hackDifficulty": 15.550000000000004,
      "minDifficulty": 10,
      "moneyAvailable": 33750000,
      "moneyMax": 126562500,
      "numOpenPortsRequired": 2,
      "openPortCount": 2,
      "requiredHackingSkill": 150,
      "serverGrowth": 30,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 4191404.0039327755,
      "hasAdminrights": true
    },
    "sigma-cosmetics": {
      "parent": "home",
      "hops": 1,
      "links": [
        "home"
      ],
      "hostname": "sigma-cosmetics",
      "ip": "53.1.0.2",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 1,
      "isConnectedTo": false,
      "ramUsed": 16,
      "maxRam": 16,
      "organizationName": "Sigma Cosmetics",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 10,
      "hackDifficulty": 3.088,
      "minDifficulty": 3,
      "moneyAvailable": 1291580.0236302724,
      "moneyMax": 6468750,
      "numOpenPortsRequired": 0,
      "openPortCount": 2,
      "requiredHackingSkill": 5,
      "serverGrowth": 10,
      "timeNextHack": 4108140.9609997454,
      "timeNextGrow": 4152980.433949427,
      "timeNextWeaken": 4159075.542436784,
      "hasAdminrights": true
    },
    "joesguns": {
      "parent": "home",
      "hops": 1,
      "links": [
        "home"
      ],
      "hostname": "joesguns",
      "ip": "74.4.7.2",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 1,
      "isConnectedTo": false,
      "ramUsed": 16,
      "maxRam": 16,
      "organizationName": "Joe's Guns",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 15,
      "hackDifficulty": 5.04,
      "minDifficulty": 5,
      "moneyAvailable": 1402488.384033638,
      "moneyMax": 7031250,
      "numOpenPortsRequired": 0,
      "openPortCount": 2,
      "requiredHackingSkill": 10,
      "serverGrowth": 20,
      "timeNextHack": 4040223.437409848,
      "timeNextGrow": 4147238.528875495,
      "timeNextWeaken": 4156198.1610943684,
      "hasAdminrights": true
    },
    "hong-fang-tea": {
      "parent": "home",
      "hops": 1,
      "links": [
        "home",
        "nectar-net",
        "CSEC"
      ],
      "hostname": "hong-fang-tea",
      "ip": "44.4.0.7",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 1,
      "isConnectedTo": false,
      "ramUsed": 16,
      "maxRam": 16,
      "organizationName": "HongFang Teahouse",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 15,
      "hackDifficulty": 5.213999999999992,
      "minDifficulty": 5,
      "moneyAvailable": 1703098.6673346865,
      "moneyMax": 8437500,
      "numOpenPortsRequired": 0,
      "openPortCount": 2,
      "requiredHackingSkill": 30,
      "serverGrowth": 20,
      "timeNextHack": 4145068.5908319238,
      "timeNextGrow": 4151090.3667665287,
      "timeNextWeaken": 4151469.0756760817,
      "hasAdminrights": true
    },
    "nectar-net": {
      "parent": "home",
      "hops": 1,
      "links": [
        "hong-fang-tea",
        "neo-net",
        "phantasy",
        "home"
      ],
      "hostname": "nectar-net",
      "ip": "71.2.7.8",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 2,
      "isConnectedTo": false,
      "ramUsed": 16,
      "maxRam": 16,
      "organizationName": "Nectar Nightclub Network",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 20,
      "hackDifficulty": 11.773999999999946,
      "minDifficulty": 7,
      "moneyAvailable": 1416093.386060042,
      "moneyMax": 7734375,
      "numOpenPortsRequired": 0,
      "openPortCount": 2,
      "requiredHackingSkill": 20,
      "serverGrowth": 25,
      "timeNextHack": 3895511.114182832,
      "timeNextGrow": 4142596.3960323487,
      "timeNextWeaken": 4167588.2715390394,
      "hasAdminrights": true
    },
    "neo-net": {
      "parent": "home",
      "hops": 1,
      "links": [
        "nectar-net",
        "computek",
        "crush-fitness",
        "home"
      ],
      "hostname": "neo-net",
      "ip": "64.8.3.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 2,
      "isConnectedTo": false,
      "ramUsed": 32,
      "maxRam": 32,
      "organizationName": "Neo Nightclub Network",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 25,
      "hackDifficulty": 8.059999999999992,
      "minDifficulty": 8,
      "moneyAvailable": 2801060.251219588,
      "moneyMax": 14062500,
      "numOpenPortsRequired": 1,
      "openPortCount": 2,
      "requiredHackingSkill": 50,
      "serverGrowth": 25,
      "timeNextHack": 3958618.6493578153,
      "timeNextGrow": 4151166.351629251,
      "timeNextWeaken": 4175109.4694085624,
      "hasAdminrights": true
    },
    "computek": {
      "parent": "neo-net",
      "hops": 4,
      "links": [
        "neo-net",
        "zb-institute"
      ],
      "hostname": "computek",
      "ip": "37.6.7.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "CompuTek",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 64,
      "hackDifficulty": 64,
      "minDifficulty": 21,
      "moneyAvailable": 177245598,
      "moneyMax": 664670992.5,
      "numOpenPortsRequired": 3,
      "openPortCount": 2,
      "requiredHackingSkill": 376,
      "serverGrowth": 58,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "zb-institute": {
      "parent": "computek",
      "hops": 5,
      "links": [
        "computek",
        "lexo-corp"
      ],
      "hostname": "zb-institute",
      "ip": "93.9.3.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 4,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 128,
      "organizationName": "ZB Institute of Technology",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 68,
      "hackDifficulty": 68,
      "minDifficulty": 23,
      "moneyAvailable": 705294292.5,
      "moneyMax": 2644853596.875,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 752,
      "serverGrowth": 80,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "lexo-corp": {
      "parent": "zb-institute",
      "hops": 6,
      "links": [
        "zb-institute"
      ],
      "hostname": "lexo-corp",
      "ip": "56.6.6.2",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 128,
      "organizationName": "LexoCorp",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 61,
      "hackDifficulty": 61,
      "minDifficulty": 20,
      "moneyAvailable": 596704156.5,
      "moneyMax": 2237640586.875,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 701,
      "serverGrowth": 56,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "crush-fitness": {
      "parent": "home",
      "hops": 1,
      "links": [
        "neo-net",
        "summit-uni",
        "home"
      ],
      "hostname": "crush-fitness",
      "ip": "93.8.6.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Crush Fitness",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 40,
      "hackDifficulty": 34.55,
      "minDifficulty": 13,
      "moneyAvailable": 42222955.5,
      "moneyMax": 158336083.125,
      "numOpenPortsRequired": 2,
      "openPortCount": 2,
      "requiredHackingSkill": 246,
      "serverGrowth": 33,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 4856881.507684206,
      "hasAdminrights": true
    },
    "summit-uni": {
      "parent": "crush-fitness",
      "hops": 5,
      "links": [
        "crush-fitness"
      ],
      "hostname": "summit-uni",
      "ip": "25.1.3.8",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 5,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 16,
      "organizationName": "Summit University",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 47,
      "hackDifficulty": 47,
      "minDifficulty": 16,
      "moneyAvailable": 223963049.25,
      "moneyMax": 839861434.6875,
      "numOpenPortsRequired": 3,
      "openPortCount": 2,
      "requiredHackingSkill": 470,
      "serverGrowth": 45,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "phantasy": {
      "parent": "home",
      "hops": 1,
      "links": [
        "nectar-net",
        "the-hub",
        "netlink",
        "johnson-ortho",
        "home"
      ],
      "hostname": "phantasy",
      "ip": "6.1.2.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 32,
      "maxRam": 32,
      "organizationName": "Phantasy Club",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 20,
      "hackDifficulty": 8.612000000000004,
      "minDifficulty": 7,
      "moneyAvailable": 11589943.189003743,
      "moneyMax": 67500000,
      "numOpenPortsRequired": 2,
      "openPortCount": 2,
      "requiredHackingSkill": 100,
      "serverGrowth": 35,
      "timeNextHack": 4072795.363696301,
      "timeNextGrow": 4168997.1267004525,
      "timeNextWeaken": 4216457.062912715,
      "hasAdminrights": true
    },
    "the-hub": {
      "parent": "home",
      "hops": 1,
      "links": [
        "phantasy",
        "home"
      ],
      "hostname": "the-hub",
      "ip": "5.1.2.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 4,
      "isConnectedTo": false,
      "ramUsed": 32,
      "maxRam": 32,
      "organizationName": "The Hub",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 36,
      "hackDifficulty": 36,
      "minDifficulty": 12,
      "moneyAvailable": 131600869.5,
      "moneyMax": 493503260.625,
      "numOpenPortsRequired": 2,
      "openPortCount": 2,
      "requiredHackingSkill": 304,
      "serverGrowth": 47,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 4291464.881728137,
      "hasAdminrights": true
    },
    "netlink": {
      "parent": "phantasy",
      "hops": 4,
      "links": [
        "phantasy",
        "rothman-uni",
        "catalyst"
      ],
      "hostname": "netlink",
      "ip": "64.0.9.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 2,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 16,
      "organizationName": "NetLink Technologies",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 78,
      "hackDifficulty": 78,
      "minDifficulty": 26,
      "moneyAvailable": 206250000,
      "moneyMax": 773437500,
      "numOpenPortsRequired": 3,
      "openPortCount": 2,
      "requiredHackingSkill": 423,
      "serverGrowth": 57,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "rothman-uni": {
      "parent": "netlink",
      "hops": 5,
      "links": [
        "netlink",
        "alpha-ent",
        "aevum-police",
        "millenium-fitness"
      ],
      "hostname": "rothman-uni",
      "ip": "30.9.5.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 4,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 64,
      "organizationName": "Rothman University",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 47,
      "hackDifficulty": 47,
      "minDifficulty": 16,
      "moneyAvailable": 182822531.25,
      "moneyMax": 685584492.1875,
      "numOpenPortsRequired": 3,
      "openPortCount": 2,
      "requiredHackingSkill": 371,
      "serverGrowth": 35,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "alpha-ent": {
      "parent": "rothman-uni",
      "hops": 6,
      "links": [
        "rothman-uni",
        "global-pharm"
      ],
      "hostname": "alpha-ent",
      "ip": "87.5.8.2",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 16,
      "organizationName": "Alpha Enterprises",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 68,
      "hackDifficulty": 68,
      "minDifficulty": 23,
      "moneyAvailable": 469657131.75,
      "moneyMax": 1761214244.0625,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 544,
      "serverGrowth": 57,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "global-pharm": {
      "parent": "alpha-ent",
      "hops": 7,
      "links": [
        "alpha-ent",
        "deltaone"
      ],
      "hostname": "global-pharm",
      "ip": "90.6.8.8",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 4,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 16,
      "organizationName": "Global Pharmaceuticals",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 75,
      "hackDifficulty": 75,
      "minDifficulty": 25,
      "moneyAvailable": 1240668675.75,
      "moneyMax": 4652507534.0625,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 768,
      "serverGrowth": 89,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "deltaone": {
      "parent": "global-pharm",
      "hops": 8,
      "links": [
        "global-pharm",
        "univ-energy"
      ],
      "hostname": "deltaone",
      "ip": "58.2.6.8",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "DeltaOne",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 77,
      "hackDifficulty": 77,
      "minDifficulty": 26,
      "moneyAvailable": 1016049162.75,
      "moneyMax": 3810184360.3125,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 872,
      "serverGrowth": 51,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "univ-energy": {
      "parent": "deltaone",
      "hops": 9,
      "links": [
        "deltaone"
      ],
      "hostname": "univ-energy",
      "ip": "26.2.8.2",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 8,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 64,
      "organizationName": "Universal Energy",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 84,
      "hackDifficulty": 84,
      "minDifficulty": 28,
      "moneyAvailable": 839139174.75,
      "moneyMax": 3146771905.3125,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 870,
      "serverGrowth": 88,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "aevum-police": {
      "parent": "rothman-uni",
      "hops": 6,
      "links": [
        "rothman-uni"
      ],
      "hostname": "aevum-police",
      "ip": "46.1.8.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 4,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 32,
      "organizationName": "Aevum Police Headquarters",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 77,
      "hackDifficulty": 77,
      "minDifficulty": 26,
      "moneyAvailable": 206341736.25,
      "moneyMax": 773781510.9375,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 407,
      "serverGrowth": 49,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "millenium-fitness": {
      "parent": "rothman-uni",
      "hops": 6,
      "links": [
        "rothman-uni",
        "galactic-cyber",
        "aerocorp",
        "snap-fitness"
      ],
      "hostname": "millenium-fitness",
      "ip": "36.9.0.6",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 4,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 16,
      "organizationName": "Millenium Fitness Network",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 51,
      "hackDifficulty": 51,
      "minDifficulty": 17,
      "moneyAvailable": 187500000,
      "moneyMax": 703125000,
      "numOpenPortsRequired": 3,
      "openPortCount": 2,
      "requiredHackingSkill": 500,
      "serverGrowth": 37,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "galactic-cyber": {
      "parent": "millenium-fitness",
      "hops": 7,
      "links": [
        "millenium-fitness"
      ],
      "hostname": "galactic-cyber",
      "ip": "96.5.8.0",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Galactic Cybersystems",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 55,
      "hackDifficulty": 55,
      "minDifficulty": 18,
      "moneyAvailable": 579319794.75,
      "moneyMax": 2172449230.3125,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 865,
      "serverGrowth": 80,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "aerocorp": {
      "parent": "millenium-fitness",
      "hops": 7,
      "links": [
        "millenium-fitness",
        "unitalife"
      ],
      "hostname": "aerocorp",
      "ip": "66.6.2.3",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 4,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "AeroCorp",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 88,
      "hackDifficulty": 88,
      "minDifficulty": 29,
      "moneyAvailable": 796103379.75,
      "moneyMax": 2985387674.0625,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 897,
      "serverGrowth": 64,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "unitalife": {
      "parent": "aerocorp",
      "hops": 8,
      "links": [
        "aerocorp",
        "defcomm",
        "solaris",
        "zeus-med"
      ],
      "hostname": "unitalife",
      "ip": "74.1.7.3",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 8,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 64,
      "organizationName": "UnitaLife Group",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 80,
      "hackDifficulty": 80,
      "minDifficulty": 27,
      "moneyAvailable": 817763883,
      "moneyMax": 3066614561.25,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 783,
      "serverGrowth": 80,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "defcomm": {
      "parent": "unitalife",
      "hops": 9,
      "links": [
        "unitalife",
        "taiyang-digital"
      ],
      "hostname": "defcomm",
      "ip": "22.4.1.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "DefComm",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 86,
      "hackDifficulty": 86,
      "minDifficulty": 29,
      "moneyAvailable": 684481979.25,
      "moneyMax": 2566807422.1875,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 880,
      "serverGrowth": 73,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "taiyang-digital": {
      "parent": "defcomm",
      "hops": 10,
      "links": [
        "defcomm",
        "run4theh111z"
      ],
      "hostname": "taiyang-digital",
      "ip": "8.1.4.8",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 9,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Taiyang Digital",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 76,
      "hackDifficulty": 76,
      "minDifficulty": 25,
      "moneyAvailable": 668879482.5,
      "moneyMax": 2508298059.375,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 851,
      "serverGrowth": 78,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "run4theh111z": {
      "parent": "taiyang-digital",
      "hops": 11,
      "links": [
        "taiyang-digital",
        "fulcrumtech",
        "stormtech"
      ],
      "hostname": "run4theh111z",
      "ip": "55.3.0.6",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 7,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 64,
      "organizationName": "The Runners",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 1,
      "hackDifficulty": 1,
      "minDifficulty": 1,
      "moneyAvailable": 0,
      "moneyMax": 0,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 508,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "fulcrumtech": {
      "parent": "run4theh111z",
      "hops": 12,
      "links": [
        "run4theh111z",
        "omnitek",
        "4sigma",
        "kuai-gong"
      ],
      "hostname": "fulcrumtech",
      "ip": "17.2.7.8",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 11,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 1024,
      "organizationName": "Fulcrum Technologies",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 84,
      "hackDifficulty": 84,
      "minDifficulty": 28,
      "moneyAvailable": 1053098196,
      "moneyMax": 3949118235,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 972,
      "serverGrowth": 81,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "omnitek": {
      "parent": "fulcrumtech",
      "hops": 13,
      "links": [
        "fulcrumtech",
        "clarkinc"
      ],
      "hostname": "omnitek",
      "ip": "59.0.8.3",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 10,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 128,
      "organizationName": "OmniTek Incorporated",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 99,
      "hackDifficulty": 99,
      "minDifficulty": 33,
      "moneyAvailable": 13834480299.75,
      "moneyMax": 51879301124.0625,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1086,
      "serverGrowth": 95,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "clarkinc": {
      "parent": "omnitek",
      "hops": 14,
      "links": [
        "omnitek"
      ],
      "hostname": "clarkinc",
      "ip": "34.2.5.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 7,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Clarke Incorporated",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 61,
      "hackDifficulty": 61,
      "minDifficulty": 20,
      "moneyAvailable": 14146530276.75,
      "moneyMax": 53049488537.8125,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1113,
      "serverGrowth": 70,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "4sigma": {
      "parent": "fulcrumtech",
      "hops": 13,
      "links": [
        "fulcrumtech"
      ],
      "hostname": "4sigma",
      "ip": "54.2.8.3",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 12,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Four Sigma",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 75,
      "hackDifficulty": 75,
      "minDifficulty": 25,
      "moneyAvailable": 15378425883,
      "moneyMax": 57669097061.25,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 900,
      "serverGrowth": 99,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "kuai-gong": {
      "parent": "fulcrumtech",
      "hops": 13,
      "links": [
        "fulcrumtech",
        "b-and-a"
      ],
      "hostname": "kuai-gong",
      "ip": "10.4.3.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 10,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "KuaiGong International",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 95,
      "hackDifficulty": 95,
      "minDifficulty": 32,
      "moneyAvailable": 19261428562.5,
      "moneyMax": 72230357109.375,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1223,
      "serverGrowth": 92,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "b-and-a": {
      "parent": "kuai-gong",
      "hops": 14,
      "links": [
        "kuai-gong"
      ],
      "hostname": "b-and-a",
      "ip": "12.7.3.0",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 10,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Bachman & Associates",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 79,
      "hackDifficulty": 79,
      "minDifficulty": 26,
      "moneyAvailable": 14008567851.75,
      "moneyMax": 52532129444.0625,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1124,
      "serverGrowth": 63,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "stormtech": {
      "parent": "run4theh111z",
      "hops": 12,
      "links": [
        "run4theh111z",
        "."
      ],
      "hostname": "stormtech",
      "ip": "69.3.5.6",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 8,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Storm Technologies",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 87,
      "hackDifficulty": 87,
      "minDifficulty": 29,
      "moneyAvailable": 779316816.75,
      "moneyMax": 2922438062.8125,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 885,
      "serverGrowth": 83,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    ".": {
      "parent": "stormtech",
      "hops": 13,
      "links": [
        "stormtech",
        "blade",
        "nwo",
        "powerhouse-fitness"
      ],
      "hostname": ".",
      "ip": "9.3.4.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 12,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 16,
      "organizationName": ".",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 1,
      "hackDifficulty": 1,
      "minDifficulty": 1,
      "moneyAvailable": 0,
      "moneyMax": 0,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 517,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "blade": {
      "parent": ".",
      "hops": 14,
      "links": [
        ".",
        "ecorp",
        "fulcrumassets",
        "The-Cave"
      ],
      "hostname": "blade",
      "ip": "13.3.8.7",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 14,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 64,
      "organizationName": "Blade Industries",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 97,
      "hackDifficulty": 97,
      "minDifficulty": 32,
      "moneyAvailable": 14080375840.5,
      "moneyMax": 52801409401.875,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1006,
      "serverGrowth": 85,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "ecorp": {
      "parent": "blade",
      "hops": 15,
      "links": [
        "blade"
      ],
      "hostname": "ecorp",
      "ip": "27.0.2.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 12,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "ECorp",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 99,
      "hackDifficulty": 99,
      "minDifficulty": 33,
      "moneyAvailable": 43189843237.5,
      "moneyMax": 161961912140.625,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1319,
      "serverGrowth": 99,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "fulcrumassets": {
      "parent": "blade",
      "hops": 15,
      "links": [
        "blade"
      ],
      "hostname": "fulcrumassets",
      "ip": "90.5.3.6",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 10,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Fulcrum Technologies",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 99,
      "hackDifficulty": 99,
      "minDifficulty": 33,
      "moneyAvailable": 750000,
      "moneyMax": 2812500,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1555,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "The-Cave": {
      "parent": "blade",
      "hops": 15,
      "links": [
        "blade"
      ],
      "hostname": "The-Cave",
      "ip": "28.1.2.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 9,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Helios",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 1,
      "hackDifficulty": 1,
      "minDifficulty": 1,
      "moneyAvailable": 0,
      "moneyMax": 0,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 925,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "nwo": {
      "parent": ".",
      "hops": 14,
      "links": [
        ".",
        "megacorp"
      ],
      "hostname": "nwo",
      "ip": "84.0.3.2",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 14,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "NWO",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 99,
      "hackDifficulty": 99,
      "minDifficulty": 33,
      "moneyAvailable": 16679951637.75,
      "moneyMax": 62549818641.5625,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1113,
      "serverGrowth": 72,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "megacorp": {
      "parent": "nwo",
      "hops": 15,
      "links": [
        "nwo"
      ],
      "hostname": "megacorp",
      "ip": "59.2.1.0",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 10,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "MegaCorp",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 99,
      "hackDifficulty": 99,
      "minDifficulty": 33,
      "moneyAvailable": 42733252286.25,
      "moneyMax": 160249696073.4375,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1202,
      "serverGrowth": 99,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "powerhouse-fitness": {
      "parent": ".",
      "hops": 14,
      "links": [
        "."
      ],
      "hostname": "powerhouse-fitness",
      "ip": "18.5.9.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 11,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 16,
      "organizationName": "Powerhouse Fitness",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 64,
      "hackDifficulty": 64,
      "minDifficulty": 21,
      "moneyAvailable": 675000000,
      "moneyMax": 2531250000,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1066,
      "serverGrowth": 51,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "solaris": {
      "parent": "unitalife",
      "hops": 9,
      "links": [
        "unitalife"
      ],
      "hostname": "solaris",
      "ip": "91.0.5.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 128,
      "organizationName": "Solaris Space Systems",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 72,
      "hackDifficulty": 72,
      "minDifficulty": 24,
      "moneyAvailable": 673134709.5,
      "moneyMax": 2524255160.625,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 793,
      "serverGrowth": 79,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "zeus-med": {
      "parent": "unitalife",
      "hops": 9,
      "links": [
        "unitalife",
        "infocomm",
        "zb-def",
        "nova-med"
      ],
      "hostname": "zeus-med",
      "ip": "3.1.0.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 5,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Zeus Medical",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 82,
      "hackDifficulty": 82,
      "minDifficulty": 27,
      "moneyAvailable": 1025667569.25,
      "moneyMax": 3846253384.6875,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 833,
      "serverGrowth": 78,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "infocomm": {
      "parent": "zeus-med",
      "hops": 10,
      "links": [
        "zeus-med"
      ],
      "hostname": "infocomm",
      "ip": "55.4.6.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 9,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "InfoComm",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 71,
      "hackDifficulty": 71,
      "minDifficulty": 24,
      "moneyAvailable": 520096869,
      "moneyMax": 1950363258.75,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 928,
      "serverGrowth": 61,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "zb-def": {
      "parent": "zeus-med",
      "hops": 10,
      "links": [
        "zeus-med",
        "titan-labs",
        "microdyne",
        "applied-energetics"
      ],
      "hostname": "zb-def",
      "ip": "71.8.6.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "ZB Defense Industries",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 65,
      "hackDifficulty": 65,
      "minDifficulty": 22,
      "moneyAvailable": 741430707.75,
      "moneyMax": 2780365154.0625,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 787,
      "serverGrowth": 73,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "titan-labs": {
      "parent": "zb-def",
      "hops": 11,
      "links": [
        "zb-def"
      ],
      "hostname": "titan-labs",
      "ip": "75.1.7.7",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 11,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 64,
      "organizationName": "Titan Laboratories",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 79,
      "hackDifficulty": 79,
      "minDifficulty": 26,
      "moneyAvailable": 639136233.75,
      "moneyMax": 2396760876.5625,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 875,
      "serverGrowth": 73,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "microdyne": {
      "parent": "zb-def",
      "hops": 11,
      "links": [
        "zb-def"
      ],
      "hostname": "microdyne",
      "ip": "77.9.9.7",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 64,
      "organizationName": "Microdyne Technologies",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 75,
      "hackDifficulty": 75,
      "minDifficulty": 25,
      "moneyAvailable": 495173868,
      "moneyMax": 1856902005,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 865,
      "serverGrowth": 78,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "applied-energetics": {
      "parent": "zb-def",
      "hops": 11,
      "links": [
        "zb-def",
        "helios",
        "vitalife"
      ],
      "hostname": "applied-energetics",
      "ip": "54.3.9.7",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 10,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Applied Energetics",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 70,
      "hackDifficulty": 70,
      "minDifficulty": 23,
      "moneyAvailable": 586011135,
      "moneyMax": 2197541756.25,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 801,
      "serverGrowth": 73,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "helios": {
      "parent": "applied-energetics",
      "hops": 12,
      "links": [
        "applied-energetics"
      ],
      "hostname": "helios",
      "ip": "31.4.9.2",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 9,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 128,
      "organizationName": "Helios Labs",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 85,
      "hackDifficulty": 85,
      "minDifficulty": 28,
      "moneyAvailable": 435220557,
      "moneyMax": 1632077088.75,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 837,
      "serverGrowth": 77,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "vitalife": {
      "parent": "applied-energetics",
      "hops": 12,
      "links": [
        "applied-energetics"
      ],
      "hostname": "vitalife",
      "ip": "69.4.9.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 10,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 64,
      "organizationName": "VitaLife",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 81,
      "hackDifficulty": 81,
      "minDifficulty": 27,
      "moneyAvailable": 565805787,
      "moneyMax": 2121771701.25,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 838,
      "serverGrowth": 63,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "nova-med": {
      "parent": "zeus-med",
      "hops": 10,
      "links": [
        "zeus-med"
      ],
      "hostname": "nova-med",
      "ip": "33.4.7.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 9,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Nova Medical",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 71,
      "hackDifficulty": 71,
      "minDifficulty": 24,
      "moneyAvailable": 924767373.75,
      "moneyMax": 3467877651.5625,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 835,
      "serverGrowth": 71,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "snap-fitness": {
      "parent": "millenium-fitness",
      "hops": 7,
      "links": [
        "millenium-fitness",
        "omnia"
      ],
      "hostname": "snap-fitness",
      "ip": "14.4.8.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 7,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Snap Fitness",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 52,
      "hackDifficulty": 52,
      "minDifficulty": 17,
      "moneyAvailable": 337500000,
      "moneyMax": 1265625000,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 685,
      "serverGrowth": 41,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "omnia": {
      "parent": "snap-fitness",
      "hops": 8,
      "links": [
        "snap-fitness",
        "icarus"
      ],
      "hostname": "omnia",
      "ip": "2.2.7.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 4,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 32,
      "organizationName": "Omnia Cybersystems",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 88,
      "hackDifficulty": 88,
      "minDifficulty": 29,
      "moneyAvailable": 727470165,
      "moneyMax": 2728013118.75,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 924,
      "serverGrowth": 60,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "icarus": {
      "parent": "omnia",
      "hops": 9,
      "links": [
        "omnia"
      ],
      "hostname": "icarus",
      "ip": "37.8.3.8",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Icarus Microsystems",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 91,
      "hackDifficulty": 91,
      "minDifficulty": 30,
      "moneyAvailable": 740839199.25,
      "moneyMax": 2778146997.1875,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 915,
      "serverGrowth": 91,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "catalyst": {
      "parent": "netlink",
      "hops": 5,
      "links": [
        "netlink",
        "rho-construction"
      ],
      "hostname": "catalyst",
      "ip": "22.2.8.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 5,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 32,
      "organizationName": "Catalyst Ventures",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 69,
      "hackDifficulty": 69,
      "minDifficulty": 23,
      "moneyAvailable": 295753745.25,
      "moneyMax": 1109076544.6875,
      "numOpenPortsRequired": 3,
      "openPortCount": 2,
      "requiredHackingSkill": 435,
      "serverGrowth": 47,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "rho-construction": {
      "parent": "catalyst",
      "hops": 6,
      "links": [
        "catalyst"
      ],
      "hostname": "rho-construction",
      "ip": "25.4.2.5",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 6,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 32,
      "organizationName": "Rho Construction",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 40,
      "hackDifficulty": 40,
      "minDifficulty": 13,
      "moneyAvailable": 436617707.25,
      "moneyMax": 1637316402.1875,
      "numOpenPortsRequired": 3,
      "openPortCount": 2,
      "requiredHackingSkill": 476,
      "serverGrowth": 51,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "johnson-ortho": {
      "parent": "home",
      "hops": 1,
      "links": [
        "phantasy",
        "syscore",
        "home"
      ],
      "hostname": "johnson-ortho",
      "ip": "61.4.1.3",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "Johnson Orthopedics",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 58,
      "hackDifficulty": 58,
      "minDifficulty": 19,
      "moneyAvailable": 59733612,
      "moneyMax": 224001045,
      "numOpenPortsRequired": 2,
      "openPortCount": 2,
      "requiredHackingSkill": 290,
      "serverGrowth": 54,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 4642798.783202399,
      "hasAdminrights": true
    },
    "syscore": {
      "parent": "johnson-ortho",
      "hops": 5,
      "links": [
        "johnson-ortho"
      ],
      "hostname": "syscore",
      "ip": "18.7.7.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "SysCore Securities",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 73,
      "hackDifficulty": 73,
      "minDifficulty": 24,
      "moneyAvailable": 439677204.75,
      "moneyMax": 1648789517.8125,
      "numOpenPortsRequired": 4,
      "openPortCount": 2,
      "requiredHackingSkill": 602,
      "serverGrowth": 70,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "CSEC": {
      "parent": "home",
      "hops": 1,
      "links": [
        "hong-fang-tea",
        "home"
      ],
      "hostname": "CSEC",
      "ip": "9.9.9.7",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 2,
      "isConnectedTo": false,
      "ramUsed": 8,
      "maxRam": 8,
      "organizationName": "CyberSec",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 1,
      "hackDifficulty": 1,
      "minDifficulty": 1,
      "moneyAvailable": 0,
      "moneyMax": 0,
      "numOpenPortsRequired": 1,
      "openPortCount": 2,
      "requiredHackingSkill": 55,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0,
      "hasAdminrights": true
    },
    "harakiri-sushi": {
      "parent": "home",
      "hops": 1,
      "links": [
        "home"
      ],
      "hostname": "harakiri-sushi",
      "ip": "8.3.2.3",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 1,
      "isConnectedTo": false,
      "ramUsed": 16,
      "maxRam": 16,
      "organizationName": "HaraKiri Sushi Bar Network",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 15,
      "hackDifficulty": 5.379999999999997,
      "minDifficulty": 5,
      "moneyAvailable": 2212047.3116411045,
      "moneyMax": 11250000,
      "numOpenPortsRequired": 0,
      "openPortCount": 2,
      "requiredHackingSkill": 40,
      "serverGrowth": 40,
      "timeNextHack": 4039699.263828841,
      "timeNextGrow": 4149368.678870229,
      "timeNextWeaken": 4171860.8485877863,
      "hasAdminrights": true
    },
    "iron-gym": {
      "parent": "home",
      "hops": 1,
      "links": [
        "home",
        "zer0"
      ],
      "hostname": "iron-gym",
      "ip": "20.8.7.8",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 1,
      "isConnectedTo": false,
      "ramUsed": 32,
      "maxRam": 32,
      "organizationName": "Iron Gym Network",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 30,
      "hackDifficulty": 21.75,
      "minDifficulty": 10,
      "moneyAvailable": 15000000,
      "moneyMax": 56250000,
      "numOpenPortsRequired": 1,
      "openPortCount": 2,
      "requiredHackingSkill": 100,
      "serverGrowth": 20,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 4213484.824446107,
      "hasAdminrights": true
    },
    "zer0": {
      "parent": "home",
      "hops": 1,
      "links": [
        "iron-gym",
        "omega-net",
        "home"
      ],
      "hostname": "zer0",
      "ip": "89.2.8.3",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 2,
      "isConnectedTo": false,
      "ramUsed": 32,
      "maxRam": 32,
      "organizationName": "ZER0 Nightclub",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 25,
      "hackDifficulty": 8.021999999999998,
      "minDifficulty": 8,
      "moneyAvailable": 3464175.518212548,
      "moneyMax": 21093750,
      "numOpenPortsRequired": 1,
      "openPortCount": 2,
      "requiredHackingSkill": 75,
      "serverGrowth": 40,
      "timeNextHack": 3628278.183237665,
      "timeNextGrow": 4170509.329657694,
      "timeNextWeaken": 4158558.076032547,
      "hasAdminrights": true
    },
    "omega-net": {
      "parent": "home",
      "hops": 1,
      "links": [
        "zer0",
        "avmnite-02h",
        "home"
      ],
      "hostname": "omega-net",
      "ip": "68.4.5.1",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 32,
      "maxRam": 32,
      "organizationName": "Omega Software",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 31,
      "hackDifficulty": 15.297999999999998,
      "minDifficulty": 10,
      "moneyAvailable": 42057719.58318503,
      "moneyMax": 172956976.875,
      "numOpenPortsRequired": 2,
      "openPortCount": 2,
      "requiredHackingSkill": 196,
      "serverGrowth": 33,
      "timeNextHack": 3047941.2154615824,
      "timeNextGrow": 3241170.702475689,
      "timeNextWeaken": 4313353.382057696,
      "hasAdminrights": true
    },
    "avmnite-02h": {
      "parent": "home",
      "hops": 1,
      "links": [
        "omega-net",
        "I.I.I.I",
        "home"
      ],
      "hostname": "avmnite-02h",
      "ip": "86.5.3.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": true,
      "cpuCores": 3,
      "isConnectedTo": false,
      "ramUsed": 128,
      "maxRam": 128,
      "organizationName": "NiteSec",
      "purchasedByPlayer": false,
      "backdoorInstalled": true,
      "baseDifficulty": 1,
      "hackDifficulty": 1,
      "minDifficulty": 1,
      "moneyAvailable": 0,
      "moneyMax": 0,
      "numOpenPortsRequired": 2,
      "openPortCount": 2,
      "requiredHackingSkill": 209,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0,
      "hasAdminrights": true
    },
    "I.I.I.I": {
      "parent": "avmnite-02h",
      "hops": 5,
      "links": [
        "avmnite-02h"
      ],
      "hostname": "I.I.I.I",
      "ip": "95.2.6.0",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 5,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 128,
      "organizationName": "I.I.I.I",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 1,
      "hackDifficulty": 1,
      "minDifficulty": 1,
      "moneyAvailable": 0,
      "moneyMax": 0,
      "numOpenPortsRequired": 3,
      "openPortCount": 2,
      "requiredHackingSkill": 352,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    },
    "darkweb": {
      "parent": "home",
      "hops": 1,
      "links": [
        "home"
      ],
      "hostname": "darkweb",
      "ip": "8.8.6.9",
      "sshPortOpen": true,
      "ftpPortOpen": true,
      "smtpPortOpen": false,
      "httpPortOpen": false,
      "sqlPortOpen": false,
      "hasAdminRights": false,
      "cpuCores": 1,
      "isConnectedTo": false,
      "ramUsed": 0,
      "maxRam": 0,
      "organizationName": "darkweb",
      "purchasedByPlayer": false,
      "backdoorInstalled": false,
      "baseDifficulty": 1,
      "hackDifficulty": 1,
      "minDifficulty": 1,
      "moneyAvailable": 0,
      "moneyMax": 0,
      "numOpenPortsRequired": 5,
      "openPortCount": 2,
      "requiredHackingSkill": 1,
      "serverGrowth": 1,
      "timeNextHack": 0,
      "timeNextGrow": 0,
      "timeNextWeaken": 0
    }
  },
  "factions": {
    "CyberSec": {
      "augmentations": [
        "NeuroFlux Governor",
        "BitWire",
        "Synaptic Enhancement Implant",
        "Cranial Signal Processors - Gen I",
        "Cranial Signal Processors - Gen II",
        "Neurotrainer I"
      ],
      "availableAugmentations": {}
    },
    "NiteSec": {
      "augmentations": [
        "NeuroFlux Governor",
        "BitWire",
        "Artificial Synaptic Potentiation",
        "Neural-Retention Enhancement",
        "DataJack",
        "Embedded Netburner Module",
        "Cranial Signal Processors - Gen I",
        "Cranial Signal Processors - Gen II",
        "Cranial Signal Processors - Gen III",
        "Neurotrainer II",
        "CRTX42-AA Gene Modification"
      ],
      "availableAugmentations": {
        "CRTX42-AA Gene Modification": {}
      }
    },
    "Sector-12": {
      "augmentations": [
        "NeuroFlux Governor",
        "Augmented Targeting I",
        "Augmented Targeting II",
        "Wired Reflexes",
        "Speech Processor Implant",
        "Neuralstimulator",
        "CashRoot Starter Kit"
      ],
      "availableAugmentations": {}
    }
  }
}